apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: agile-assistant
  labels:
    app.kubernetes.io/part-of: agile-assistant
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
