apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: agile-assistant
  labels:
    app: postgres
    app.kubernetes.io/part-of: agile-assistant
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
