apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: agile-assistant
  labels:
    app: qdrant
    app.kubernetes.io/part-of: agile-assistant
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
