apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: agile-assistant
  labels:
    app: streamlit
    app.kubernetes.io/part-of: agile-assistant
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
